version: 2.1
orbs:
  python: circleci/python@2.0.3
  aws-cli: circleci/aws-cli@3.1.4
  ansible-playbook: orbss/ansible-playbook@0.0.5
  ruby: circleci/ruby@2.0.0

jobs:
  cfn-lint:
    executor: python/default
    steps:
      - checkout
      - run: pip install cfn-lint
      - run:
          name: run cfn-lint
          command: |
            cfn-lint -i W3002 -t cloudformation/*.yml
  executeCloudFormation:
    executor: aws-cli/default
    steps:
      - checkout
      - aws-cli/setup:
          aws-access-key-id: AWS_ACCESS_KEY_ID
          aws-secret-access-key: AWS_SECRET_ACCESS_KEY
          aws-region: AWS_DEFAULT_REGION
      - run: 
          name: deploy Cloudformation
          command: |
            set -x
            aws cloudformation deploy --template cloudformation/lecture10VPC.yml --stack-name VPCtest
            aws cloudformation deploy --template cloudformation/lecture10SG.yml --stack-name SGtest
            aws cloudformation deploy --template cloudformation/lecture10EC2.yml --stack-name EC2test2

      - run:
          name: RDS endpoint set
          command: |
            mkdir -p /tmp/workspace
            RDS_ENDPOINT=$(aws rds describe-db-instances \
              --db-instance-identifier cloudformationRDS \
              --query "DBInstances[*].Endpoint.Address" \
              --output text > /tmp/workspace/rds-endpoint.txt)
            cat /tmp/workspace/rds-endpoint.txt
            aws elbv2 describe-load-balancers --names cloudformationALB --query "LoadBalancers[].DNSName" --output text> /tmp/workspace/alb-dns.txt

      - persist_to_workspace:
          root: /tmp/workspace
          paths:
            - rds-endpoint.txt
            - alb-dns.txt
  executeAnsible:
    executor: ansible-playbook/default
    steps:
      - checkout
      - add_ssh_keys:
          fingerprints:
            - 66:73:7c:32:df:2a:c0:21:90:ab:eb:09:27:28:a7:50
      - ansible-playbook/install:
          version: '2.10.7'
      - run: 
          name: vaultpass setting
          command: |
            echo "$ANSIBLE_VAULT_PASSWORD" > env.txt
      - run: 
          name: ACCESS KEY setting
          command: |
            set -x
            echo export ACCESS_KEY_ID=$AWS_ACCESS_KEY_ID >> $BASH_ENV
            echo export SECRET_ACCESS_KEY=$AWS_SECRET_ACCESS_KEY >> $BASH_ENV
            source $BASH_ENV

      - attach_workspace:
          at: /tmp/workspace
      - run: cat /tmp/workspace/rds-endpoint.txt
      - run: cat /tmp/workspace/alb-dns.txt
      - ansible-playbook/playbook:
          playbook: ansible/playbook.yml
          playbook-options: '-u ec2-user -i ansible/hosts/inventory --private-key ~/.ssh/id_rsa --extra-vars "RDS_ENDPOINT=$(cat /tmp/workspace/rds-endpoint.txt)" --extra-vars "ALB_DNS=$(cat /tmp/workspace/alb-dns.txt)"'

  executeServerspec:
    docker:
      - image: 'cimg/base:stable'
    steps:
      - checkout
      - ruby/install:
          version: '3.1.2'
      - attach_workspace:
          at: /tmp/workspace
      - run: cat /tmp/workspace/alb-dns.txt
      - run:
          name: executeServerspec
          command: |
            cd serverSpec
            gem install bundler
            gem install serverspec
            gem install rake
            gem install ed25519
            gem install bcrypt_pbkdf
            env ALB_DNS=$(cat /tmp/workspace/alb-dns.txt) rake spec

workflows:
  raisetech:
    jobs:
      - cfn-lint
      - executeCloudFormation:
          requires:
            - cfn-lint
      - executeAnsible:
          requires:
            - executeCloudFormation
      - executeServerspec:
          requires:
            - executeAnsible